### ISSUE TITLE
It would be better to order papers from newest to oldest 

### ISSUE THREAD

**Issue by abduallahmohamed** [Psychic-DL/Awesome-Traffic-Agent-Trajectory-Prediction#2]
Thanks for your effort. 

I think it's beneficial to order papers from newest to oldest. Aka 2022 ---> 2020.

**Comment by Psychic-DL** [comment]
> Thanks for your effort.
> 
> I think it's beneficial to order papers from newest to oldest. Aka 2022 ---> 2020.

**Comment by Psychic-DL** [comment]
> Thanks for your effort.
> 
> I think it's beneficial to order papers from newest to oldest. Aka 2022 ---> 2020.

Thank you for your reminder and constructive suggestion. I will deal with it at my own convenience.
