### ISSUE TITLE
Add dataset column？

### ISSUE THREAD

**Issue by yancie-yjr** [Psychic-DL/Awesome-Traffic-Agent-Trajectory-Prediction#5]
Hello, the Awesome project is nice! I suggest you can add the corresponding dataset benchmarks for each paper.

**Comment by Psychic-DL** [comment]
> Hello, the Awesome project is nice! I suggest you can add the corresponding dataset benchmarks for each paper.

Thank you for your constructive suggestion. I will continue to maintain this project at my convenience.
